# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '经济法.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import 主界面
from PyQt5 import QtCore, QtGui, QtWidgets
import 经济法题包选择界面
import 经济法错题选择
from PyQt5.QtGui import QIcon

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()

        # 图标
        self.setWindowIcon(QIcon('会计.jpg'))

        self.setObjectName("self")
        self.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(310, 80, 191, 321))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)


        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "经济法"))
        self.pushButton.setText(_translate("self", "章节练习"))
        self.pushButton_2.setText(_translate("self", "错题回顾"))
        self.pushButton_3.setText(_translate("self", "模拟考试"))
        self.pushButton_4.setText(_translate("self", "退出"))

        self.bang_ding_xin_hao_cao()

    def bang_ding_xin_hao_cao(self):
        self.pushButton_4.clicked.connect(self.tui_chu)
        self.pushButton.clicked.connect(self.zhang_jie_lian_xi)
        self.pushButton_2.clicked.connect(self.cuo_ti_hui_gu)


    def tui_chu(self):
        self.close()
        self.open_zhujiemian = 主界面.Ui_MainWindow()
        self.open_zhujiemian.show()

    def zhang_jie_lian_xi(self):
        self.close()
        self.open_tibaoxuanze = 经济法题包选择界面.Ui_MainWindow()
        self.open_tibaoxuanze.show()

    def cuo_ti_hui_gu(self):
        self.close()
        self.open_cuo_ti = 经济法错题选择.Ui_MainWindow()
        self.open_cuo_ti.show()
