# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '会计实务错题回顾.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import 经济法选择界面
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import 经济法错题答题界面

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()


        # 图标
        self.setWindowIcon(QIcon('会计.jpg'))

        self.setObjectName("self")
        self.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(220, 60, 351, 411))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 3, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 3, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 4, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 4, 1, 1, 1)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)


        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "经济法错题"))
        self.pushButton.setText(_translate("self", "错题1"))
        self.pushButton_2.setText(_translate("self", "错题2"))
        self.pushButton_3.setText(_translate("self", "错题3"))
        self.pushButton_4.setText(_translate("self", "错题4"))
        self.pushButton_5.setText(_translate("self", "错题5"))
        self.pushButton_6.setText(_translate("self", "错题6"))
        self.pushButton_7.setText(_translate("self", "错题7"))
        self.pushButton_8.setText(_translate("self", "错题8"))
        self.pushButton_9.setText(_translate("self", "错题9"))
        self.pushButton_10.setText(_translate("self", "退出"))

        self.bang_ding_xin_hao_cao()


    def bang_ding_xin_hao_cao(self):
        self.pushButton_10.clicked.connect(self.tui_chu)
        self.pushButton.clicked.connect(lambda :self.cuo_ti("错题1"))
        self.pushButton_2.clicked.connect(lambda :self.cuo_ti("错题2"))
        self.pushButton_3.clicked.connect(lambda :self.cuo_ti("错题3"))
        self.pushButton_4.clicked.connect(lambda :self.cuo_ti("错题4"))
        self.pushButton_5.clicked.connect(lambda :self.cuo_ti("错题5"))
        self.pushButton_6.clicked.connect(lambda :self.cuo_ti("错题6"))
        self.pushButton_7.clicked.connect(lambda :self.cuo_ti("错题7"))
        self.pushButton_8.clicked.connect(lambda :self.cuo_ti("错题8"))
        self.pushButton_9.clicked.connect(lambda :self.cuo_ti("错题9"))

    def tui_chu(self):
        self.close()
        self.open_xuan_ze_jie_mian = 经济法选择界面.Ui_MainWindow()
        self.open_xuan_ze_jie_mian.show()

    def cuo_ti(self,cuoti):
        self.close()
        self.open_cuoti = 经济法错题答题界面.Ui_MainWindow("jing_ji_fa.db",cuoti)
        self.open_cuoti.show()
