# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '答题界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import *
from PyQt5.QtGui import QTextCursor
import 数据库操作
import 经济法题包选择界面
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self,tiku,ti_bao):

        super(Ui_MainWindow, self).__init__()

        # 图标
        self.setWindowIcon(QIcon('会计.jpg'))

        self.tiku = tiku
        self.ti_bao = ti_bao

        self.num_1 = 1
        self.id, self.question, self.answer, self.parsing = 数据库操作.createDB(self.tiku,self.num_1,self.ti_bao)
        # 题数
        self.total_tishu = 数据库操作.getTotalRecordCount(self.tiku,self.ti_bao)

        # 行数
        if self.total_tishu // 4 == 0:
            self.hang_shu = self.total_tishu // 4
        else:
            self.hang_shu = self.total_tishu // 4 + 1

        self.font = QtGui.QFont()
        # 字体
        self.font.setFamily('微软雅黑')
        # 加粗
        self.font.setBold(False)
        # # 大小
        self.font.setPointSize(13)

        self.bu_ju()


    def bu_ju(self):
        self.setObjectName("self")
        self.resize(1079, 720)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(450, 10, 621, 251))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(450, 260, 621, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout.addWidget(self.checkBox_4)
        self.pushButton_next = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout.addWidget(self.pushButton_next)
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(980, 510, 93, 28))
        self.pushButton_close.setObjectName("pushButton_close")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(840, 350, 231, 151))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(450, 350, 391, 301))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(3, 11, 441, 651))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 1, 3, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 2, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 2, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 2, 3, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 3, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.widget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 3, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.widget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 3, 2, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.widget)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 3, 3, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.widget)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 4, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.widget)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 4, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.widget)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 4, 2, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.widget)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 4, 3, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.widget)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 5, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.widget)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_22, 5, 1, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.widget)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout.addWidget(self.pushButton_23, 5, 2, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.widget)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 5, 3, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.widget)
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout.addWidget(self.pushButton_25, 6, 0, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.widget)
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout.addWidget(self.pushButton_26, 6, 1, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.widget)
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout.addWidget(self.pushButton_27, 6, 2, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.widget)
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout.addWidget(self.pushButton_28, 6, 3, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.widget)
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout.addWidget(self.pushButton_29, 7, 0, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.widget)
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout.addWidget(self.pushButton_30, 7, 1, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.widget)
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout.addWidget(self.pushButton_31, 7, 2, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.widget)
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout.addWidget(self.pushButton_32, 7, 3, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.widget)
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout.addWidget(self.pushButton_33, 8, 0, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(self.widget)
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout.addWidget(self.pushButton_34, 8, 1, 1, 1)
        self.pushButton_35 = QtWidgets.QPushButton(self.widget)
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout.addWidget(self.pushButton_35, 8, 2, 1, 1)
        self.pushButton_36 = QtWidgets.QPushButton(self.widget)
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout.addWidget(self.pushButton_36, 8, 3, 1, 1)
        self.pushButton_37 = QtWidgets.QPushButton(self.widget)
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout.addWidget(self.pushButton_37, 9, 0, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(self.widget)
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout.addWidget(self.pushButton_38, 9, 1, 1, 1)
        self.pushButton_39 = QtWidgets.QPushButton(self.widget)
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout.addWidget(self.pushButton_39, 9, 2, 1, 1)
        self.pushButton_40 = QtWidgets.QPushButton(self.widget)
        self.pushButton_40.setObjectName("pushButton_40")
        self.gridLayout.addWidget(self.pushButton_40, 9, 3, 1, 1)
        self.pushButton_41 = QtWidgets.QPushButton(self.widget)
        self.pushButton_41.setObjectName("pushButton_41")
        self.gridLayout.addWidget(self.pushButton_41, 10, 0, 1, 1)
        self.pushButton_42 = QtWidgets.QPushButton(self.widget)
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout.addWidget(self.pushButton_42, 10, 1, 1, 1)
        self.pushButton_43 = QtWidgets.QPushButton(self.widget)
        self.pushButton_43.setObjectName("pushButton_43")
        self.gridLayout.addWidget(self.pushButton_43, 10, 2, 1, 1)
        self.pushButton_44 = QtWidgets.QPushButton(self.widget)
        self.pushButton_44.setObjectName("pushButton_44")
        self.gridLayout.addWidget(self.pushButton_44, 10, 3, 1, 1)
        self.pushButton_45 = QtWidgets.QPushButton(self.widget)
        self.pushButton_45.setObjectName("pushButton_45")
        self.gridLayout.addWidget(self.pushButton_45, 11, 0, 1, 1)
        self.pushButton_46 = QtWidgets.QPushButton(self.widget)
        self.pushButton_46.setObjectName("pushButton_46")
        self.gridLayout.addWidget(self.pushButton_46, 11, 1, 1, 1)
        self.pushButton_47 = QtWidgets.QPushButton(self.widget)
        self.pushButton_47.setObjectName("pushButton_47")
        self.gridLayout.addWidget(self.pushButton_47, 11, 2, 1, 1)
        self.pushButton_48 = QtWidgets.QPushButton(self.widget)
        self.pushButton_48.setObjectName("pushButton_48")
        self.gridLayout.addWidget(self.pushButton_48, 11, 3, 1, 1)
        self.pushButton_49 = QtWidgets.QPushButton(self.widget)
        self.pushButton_49.setObjectName("pushButton_49")
        self.gridLayout.addWidget(self.pushButton_49, 12, 0, 1, 1)
        self.pushButton_50 = QtWidgets.QPushButton(self.widget)
        self.pushButton_50.setObjectName("pushButton_50")
        self.gridLayout.addWidget(self.pushButton_50, 12, 1, 1, 1)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1079, 25))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)


        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "经济法答题界面"))
        self.plainTextEdit.setPlainText(_translate("self", self.question))
        self.checkBox.setText(_translate("self", "A"))
        self.checkBox_2.setText(_translate("self", "B"))
        self.checkBox_3.setText(_translate("self", "C"))
        self.checkBox_4.setText(_translate("self", "D"))
        self.pushButton_next.setText(_translate("self", "下一题"))
        self.pushButton_close.setText(_translate("self", "退出"))
        self.label.setText(_translate("self", "你的答案:"))
        self.lineEdit.setText(_translate("self", ""))
        self.label_2.setText(_translate("self", "正确答案:"))
        self.lineEdit_2.setText(_translate("self", ""))
        self.plainTextEdit_2.setPlainText(_translate("self", ""))
        self.pushButton.setText(_translate("self", "1"))
        self.pushButton_2.setText(_translate("self", "2"))
        self.pushButton_3.setText(_translate("self", "3"))
        self.pushButton_4.setText(_translate("self", "4"))
        self.pushButton_5.setText(_translate("self", "5"))
        self.pushButton_6.setText(_translate("self", "6"))
        self.pushButton_7.setText(_translate("self", "7"))
        self.pushButton_8.setText(_translate("self", "8"))
        self.pushButton_9.setText(_translate("self", "9"))
        self.pushButton_10.setText(_translate("self", "10"))
        self.pushButton_11.setText(_translate("self", "11"))
        self.pushButton_12.setText(_translate("self", "12"))
        self.pushButton_13.setText(_translate("self", "13"))
        self.pushButton_14.setText(_translate("self", "14"))
        self.pushButton_15.setText(_translate("self", "15"))
        self.pushButton_16.setText(_translate("self", "16"))
        self.pushButton_17.setText(_translate("self", "17"))
        self.pushButton_18.setText(_translate("self", "18"))
        self.pushButton_19.setText(_translate("self", "19"))
        self.pushButton_20.setText(_translate("self", "20"))
        self.pushButton_21.setText(_translate("self", "21"))
        self.pushButton_22.setText(_translate("self", "22"))
        self.pushButton_23.setText(_translate("self", "23"))
        self.pushButton_24.setText(_translate("self", "24"))
        self.pushButton_25.setText(_translate("self", "25"))
        self.pushButton_26.setText(_translate("self", "26"))
        self.pushButton_27.setText(_translate("self", "27"))
        self.pushButton_28.setText(_translate("self", "28"))
        self.pushButton_29.setText(_translate("self", "29"))
        self.pushButton_30.setText(_translate("self", "30"))
        self.pushButton_31.setText(_translate("self", "31"))
        self.pushButton_32.setText(_translate("self", "32"))
        self.pushButton_33.setText(_translate("self", "33"))
        self.pushButton_34.setText(_translate("self", "34"))
        self.pushButton_35.setText(_translate("self", "35"))
        self.pushButton_36.setText(_translate("self", "36"))
        self.pushButton_37.setText(_translate("self", "37"))
        self.pushButton_38.setText(_translate("self", "38"))
        self.pushButton_39.setText(_translate("self", "39"))
        self.pushButton_40.setText(_translate("self", "40"))
        self.pushButton_41.setText(_translate("self", "41"))
        self.pushButton_42.setText(_translate("self", "42"))
        self.pushButton_43.setText(_translate("self", "43"))
        self.pushButton_44.setText(_translate("self", "44"))
        self.pushButton_45.setText(_translate("self", "45"))
        self.pushButton_46.setText(_translate("self", "46"))
        self.pushButton_47.setText(_translate("self", "47"))
        self.pushButton_48.setText(_translate("self", "48"))
        self.pushButton_49.setText(_translate("self", "49"))
        self.pushButton_50.setText(_translate("self", "50"))

        self.zi_ti_yang_shi(self.font)
        self.bang_ding_xin_hao_cao()

    def bang_ding_xin_hao_cao(self):

        self.pushButton_next.clicked.connect(self.xia_yi_ti)
        self.pushButton_close.clicked.connect(self.tui_chu)

        self.pushButton.clicked.connect(lambda: self.ti_hao(1))
        self.pushButton_2.clicked.connect(lambda: self.ti_hao(2))
        self.pushButton_3.clicked.connect(lambda: self.ti_hao(3))
        self.pushButton_4.clicked.connect(lambda: self.ti_hao(4))
        self.pushButton_5.clicked.connect(lambda: self.ti_hao(5))
        self.pushButton_6.clicked.connect(lambda: self.ti_hao(6))
        self.pushButton_7.clicked.connect(lambda: self.ti_hao(7))
        self.pushButton_8.clicked.connect(lambda: self.ti_hao(8))
        self.pushButton_9.clicked.connect(lambda: self.ti_hao(9))
        self.pushButton_10.clicked.connect(lambda: self.ti_hao(10))
        self.pushButton_11.clicked.connect(lambda: self.ti_hao(11))
        self.pushButton_12.clicked.connect(lambda: self.ti_hao(12))
        self.pushButton_13.clicked.connect(lambda: self.ti_hao(13))
        self.pushButton_14.clicked.connect(lambda: self.ti_hao(14))
        self.pushButton_15.clicked.connect(lambda: self.ti_hao(15))
        self.pushButton_16.clicked.connect(lambda: self.ti_hao(16))
        self.pushButton_17.clicked.connect(lambda: self.ti_hao(17))
        self.pushButton_18.clicked.connect(lambda: self.ti_hao(18))
        self.pushButton_19.clicked.connect(lambda: self.ti_hao(19))
        self.pushButton_20.clicked.connect(lambda: self.ti_hao(20))
        self.pushButton_21.clicked.connect(lambda: self.ti_hao(21))
        self.pushButton_22.clicked.connect(lambda: self.ti_hao(22))
        self.pushButton_23.clicked.connect(lambda: self.ti_hao(23))
        self.pushButton_24.clicked.connect(lambda: self.ti_hao(24))
        self.pushButton_25.clicked.connect(lambda: self.ti_hao(25))
        self.pushButton_26.clicked.connect(lambda: self.ti_hao(26))
        self.pushButton_27.clicked.connect(lambda: self.ti_hao(27))
        self.pushButton_28.clicked.connect(lambda: self.ti_hao(28))
        self.pushButton_29.clicked.connect(lambda: self.ti_hao(29))
        self.pushButton_30.clicked.connect(lambda: self.ti_hao(30))
        self.pushButton_31.clicked.connect(lambda: self.ti_hao(31))
        self.pushButton_32.clicked.connect(lambda: self.ti_hao(32))
        self.pushButton_33.clicked.connect(lambda: self.ti_hao(33))
        self.pushButton_34.clicked.connect(lambda: self.ti_hao(34))
        self.pushButton_35.clicked.connect(lambda: self.ti_hao(35))
        self.pushButton_36.clicked.connect(lambda: self.ti_hao(36))
        self.pushButton_37.clicked.connect(lambda: self.ti_hao(37))
        self.pushButton_38.clicked.connect(lambda: self.ti_hao(38))
        self.pushButton_39.clicked.connect(lambda: self.ti_hao(39))
        self.pushButton_40.clicked.connect(lambda: self.ti_hao(40))
        self.pushButton_41.clicked.connect(lambda: self.ti_hao(41))
        self.pushButton_42.clicked.connect(lambda: self.ti_hao(42))
        self.pushButton_43.clicked.connect(lambda: self.ti_hao(43))
        self.pushButton_44.clicked.connect(lambda: self.ti_hao(44))
        self.pushButton_45.clicked.connect(lambda: self.ti_hao(45))
        self.pushButton_46.clicked.connect(lambda: self.ti_hao(46))
        self.pushButton_47.clicked.connect(lambda: self.ti_hao(47))
        self.pushButton_48.clicked.connect(lambda: self.ti_hao(48))
        self.pushButton_49.clicked.connect(lambda: self.ti_hao(49))
        self.pushButton_50.clicked.connect(lambda: self.ti_hao(50))







    def zi_ti_yang_shi(self,font):
        #设置字体样式
        self.plainTextEdit.setFont(font)
        self.plainTextEdit_2.setFont(font)
        #设置为不可编辑
        #self.lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.plainTextEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.plainTextEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
    def tui_chu(self):
        self.close()
        self.open_ti_bao_xuan_ze = 经济法题包选择界面.Ui_MainWindow()
        self.open_ti_bao_xuan_ze.show()

    def ti_hao(self,tihao):
        if tihao <= self.total_tishu:
            self.num_1 = tihao
            self.id, self.question, self.answer, self.parsing = 数据库操作.createDB(self.tiku,self.num_1,self.ti_bao)
            self.lineEdit.clear()
            self.lineEdit_2.clear()
            self.plainTextEdit_2.clear()
            self.plainTextEdit.clear()
            self.plainTextEdit.appendPlainText(self.question)


    def qing_li(self):
        #先将文本框清理

        self.lineEdit_2.clear()
        self.plainTextEdit_2.clear()
        #如果有选项选中执行
        if self.checkBox.isChecked() == True or self.checkBox_2.isChecked() == True or self.checkBox_3.isChecked() == True or self.checkBox_4.isChecked() == True:
            self.lineEdit.clear()

        if self.checkBox.isChecked() == True:
            self.checkBox.click()
            self.lineEdit.insert("A")
        if self.checkBox_2.isChecked() == True:
            self.lineEdit.insert('B')
            self.checkBox_2.click()
        if self.checkBox_3.isChecked() == True:
            self.lineEdit.insert('C')
            self.checkBox_3.click()
        if self.checkBox_4.isChecked() == True:
            self.lineEdit.insert('D')
            self.checkBox_4.click()
        self.lineEdit_2.insert(self.answer)



        #正确
        if self.lineEdit.text() == self.lineEdit_2.text():
            if self.num_1 < self.total_tishu:
                self.num_1+=1
                self.id,self.question,self.answer,self.parsing = 数据库操作.createDB(self.tiku,self.num_1,self.ti_bao)
                self.bu_ju()
            else:
                QMessageBox.information(self, "提示", "已经为最后一题")


        else:
            self.xie_ru_cuo_ti_ku()
            #self.plainTextEdit_2.appendPlainText(self.parsing)
        # else:#没有选中的直接跳过该题
        #     pass


    def xie_ru_cuo_ti_ku(self):
        数据库操作.xie_ru(self.tiku,'错题'+str(self.ti_bao[-1]),self.id,str(self.question),str(self.answer),str(self.parsing))


    def xia_yi_ti(self):

        self.qing_li()